#
# Copyright (C) BlockWorks Consulting Ltd - All Rights Reserved.
# Unauthorized copying of this file, via any medium is strictly prohibited.
# Proprietary and confidential.
# Written by Steve Tickle <Steve@BlockWorks.co>, September 2014.
#



#
#
#
BLOCKWORKS_PLATFORM=$(BLOCKWORKS_PLATFORM_BASE)/$(PLATFORM)


#
#
#
INCLUDES=-I../$(PLATFORM)
INCLUDES+=-I../
INCLUDES+=-I$(BLOCKWORKS_PLATFORM)/Common
INCLUDES+=-I$(BLOCKWORKS_PLATFORM)

OBJS=\
SimpleTests.o

include $(BLOCKWORKS_PLATFORM)/Makefile






